# How good are the existing models and datasets?

In [1]:
import pandas as pd
import os,json

model_name_list = ["CommitGen","CoDiSum","NMT","PtrGNCMsg","NNGen","ATOM"]
dataset_name_list = ["Commitgen","NNGen","CoDiSum","MCMD/java/split_random"]

## Table IV models performance

### CommitGen<sub>data</sub>

In [2]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=model_name_list)
for model_name in model_name_list:
    dataset_name = "Commitgen"
    if model_name == "ATOM":
        continue
    ref_path = "../experiment_results/model_{}/data_{}/ref.msg".format(model_name,dataset_name)
    gen_path = "../experiment_results/model_{}/data_{}/gen.msg".format(model_name,dataset_name)
    BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
    results['B-Moses'][model_name] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
    BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
    results['B-Norm'][model_name] = float(os.popen(BN_evaluate_cmd).read())
    BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['B-CC'][model_name] = float(os.popen(BC_evaluate_cmd).read().strip())
    Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
    rouge_dict = json.loads(rouge_str)
    results['Rouge-1'][model_name], results['Rouge-2'][model_name], results['Rouge-L'][model_name] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
    Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['Meteor'][model_name] = float(os.popen(Meteor_evaluate_cmd).read().strip())
pd.options.display.float_format = '{:.2f}'.format
results

          B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen   34.03  31.11 26.00   33.56   24.54   33.30  33.28
CoDiSum      0.00   6.88  0.49   11.64    0.03   11.64   4.57
NMT         32.09  26.66 21.51   28.46   20.22   28.30  27.87
PtrGNCMsg   35.41  29.88 24.82   34.99   23.96   34.77  31.79
NNGen       38.54  34.74 29.45   38.55   28.57   38.21  37.49
ATOM          NaN    NaN   NaN     NaN     NaN     NaN    NaN

### NNGen<sub>data</sub>

In [3]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=model_name_list)
for model_name in model_name_list:
    dataset_name = "NNGen"
    if model_name == "ATOM":
        continue
    ref_path = "../experiment_results/model_{}/data_{}/ref.msg".format(model_name,dataset_name)
    gen_path = "../experiment_results/model_{}/data_{}/gen.msg".format(model_name,dataset_name)
    BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
    results['B-Moses'][model_name] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
    BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
    results['B-Norm'][model_name] = float(os.popen(BN_evaluate_cmd).read())
    BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['B-CC'][model_name] = float(os.popen(BC_evaluate_cmd).read().strip())
    Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
    rouge_dict = json.loads(rouge_str)
    results['Rouge-1'][model_name], results['Rouge-2'][model_name], results['Rouge-L'][model_name] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
    Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['Meteor'][model_name] = float(os.popen(Meteor_evaluate_cmd).read().strip())
pd.options.display.float_format = '{:.2f}'.format
results

          B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen   15.08  21.60 15.48   24.57   14.51   24.29  24.35
CoDiSum      0.00   8.03  0.86   11.32    0.45   11.32   4.82
NMT          7.46  13.82  8.28   15.92    7.04   15.74  15.43
PtrGNCMsg    9.69  19.00 10.39   23.47    9.41   23.12  19.19
NNGen       16.41  23.07 16.77   27.43   15.73   27.00  26.56
ATOM          NaN    NaN   NaN     NaN     NaN     NaN    NaN

### CoDiSum<sub>data</sub>

In [4]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=model_name_list)
for model_name in model_name_list:
    dataset_name = "CoDiSum"
    if model_name == "ATOM":
        continue
    ref_path = "../experiment_results/model_{}/data_{}/ref.msg".format(model_name,dataset_name)
    gen_path = "../experiment_results/model_{}/data_{}/gen.msg".format(model_name,dataset_name)
    BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
    results['B-Moses'][model_name] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
    BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
    results['B-Norm'][model_name] = float(os.popen(BN_evaluate_cmd).read())
    BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['B-CC'][model_name] = float(os.popen(BC_evaluate_cmd).read().strip())
    Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
    rouge_dict = json.loads(rouge_str)
    results['Rouge-1'][model_name], results['Rouge-2'][model_name], results['Rouge-L'][model_name] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
    Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['Meteor'][model_name] = float(os.popen(Meteor_evaluate_cmd).read().strip())
pd.options.display.float_format = '{:.2f}'.format
results

          B-Moses B-Norm B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen    1.33   9.37 4.17   10.73    2.27   10.59   9.83
CoDiSum      1.74  15.45 5.72   19.00    4.66   18.62  12.30
NMT          1.32   9.93 3.81   11.24    2.26   11.11   9.61
PtrGNCMsg    0.81  12.72 4.77   16.43    3.58   16.06  12.16
NNGen        3.04   9.07 5.27   10.79    3.31   10.53  10.62
ATOM          NaN    NaN  NaN     NaN     NaN     NaN    NaN

### MCMD<sub>Java</sub>

In [5]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=model_name_list)
for model_name in model_name_list:
    dataset_name = "MCMD/java/split_random"
    ref_path = "../experiment_results/model_{}/data_{}/ref.msg".format(model_name,dataset_name)
    gen_path = "../experiment_results/model_{}/data_{}/gen.msg".format(model_name,dataset_name)
    BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
    results['B-Moses'][model_name] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
    BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
    results['B-Norm'][model_name] = float(os.popen(BN_evaluate_cmd).read())
    BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['B-CC'][model_name] = float(os.popen(BC_evaluate_cmd).read().strip())
    Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
    rouge_dict = json.loads(rouge_str)
    results['Rouge-1'][model_name], results['Rouge-2'][model_name], results['Rouge-L'][model_name] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
    Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
    results['Meteor'][model_name] = float(os.popen(Meteor_evaluate_cmd).read().strip())
pd.options.display.float_format = '{:.2f}'.format
results

          B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen    6.29  12.39  7.67   13.06    6.23   12.94  14.16
CoDiSum      2.00  14.00  5.37   16.84    4.43   16.51  11.34
NMT          9.17  13.39 10.24   15.47    7.78   15.33  16.00
PtrGNCMsg    8.25  15.33 11.70   19.09    8.32   18.64  19.13
NNGen       13.30  17.81 14.46   21.49   11.50   20.87  22.11
ATOM         7.47  16.42  9.29   19.10    9.58   18.60  20.80

## Table V noisy data ablation study

### Training: CommitGen<sub>data</sub>

#### Test: NNGen<sub>data</sub>

In [9]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=["CommitGen_data"])
ref_path = "../experiment_results/model_CommitGen/data_Commitgen/test_NNGen/ref.msg"
gen_path = "../experiment_results/model_CommitGen/data_Commitgen/test_NNGen/gen.msg"
BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
results['B-Moses']["CommitGen_data"] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
results['B-Norm']["CommitGen_data"] = float(os.popen(BN_evaluate_cmd).read())
BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['B-CC']["CommitGen_data"] = float(os.popen(BC_evaluate_cmd).read().strip())
Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
rouge_dict = json.loads(rouge_str)
results['Rouge-1']["CommitGen_data"], results['Rouge-2']["CommitGen_data"], results['Rouge-L']["CommitGen_data"] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['Meteor']["CommitGen_data"] = float(os.popen(Meteor_evaluate_cmd).read().strip())
pd.options.display.float_format = '{:.2f}'.format
results

               B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen_data   11.38  19.09 12.86   21.93   11.51   21.63  21.73

#### Test: Nosiy data

In [10]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=["CommitGen_data"])
ref_path = "../experiment_results/model_CommitGen/data_Commitgen/test_BotTrivial/ref.msg"
gen_path = "../experiment_results/model_CommitGen/data_Commitgen/test_BotTrivial/gen.msg"
BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
results['B-Moses']["CommitGen_data"] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
results['B-Norm']["CommitGen_data"] = float(os.popen(BN_evaluate_cmd).read())
BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['B-CC']["CommitGen_data"] = float(os.popen(BC_evaluate_cmd).read().strip())
Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
rouge_dict = json.loads(rouge_str)
results['Rouge-1']["CommitGen_data"], results['Rouge-2']["CommitGen_data"], results['Rouge-L']["CommitGen_data"] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['Meteor']["CommitGen_data"] = float(os.popen(Meteor_evaluate_cmd).read().strip())
results

               B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
CommitGen_data   97.44  94.43 95.00   94.78   93.11   94.71  93.86

### Training: NNGen<sub>data</sub>

#### Test: NNGen<sub>data</sub>

In [11]:
results = pd.DataFrame(columns=['B-Moses', 'B-Norm', 'B-CC', 'Rouge-1', 'Rouge-2', 'Rouge-L', 'Meteor'], index=["NNGen_data"])
ref_path = "../experiment_results/model_CommitGen/data_NNGen/ref.msg"
gen_path = "../experiment_results/model_CommitGen/data_NNGen/gen.msg"
BM_evaluate_cmd = "../metrics/B-Moses.perl {} < {}".format(ref_path, gen_path)
results['B-Moses']["NNGen_data"] = float(os.popen(BM_evaluate_cmd).read().split("=")[1].split(",")[0].strip())
BN_evaluate_cmd = "python ../metrics/B-Norm.py {} < {}".format(ref_path, gen_path)
results['B-Norm']["NNGen_data"] = float(os.popen(BN_evaluate_cmd).read())
BC_evaluate_cmd = "python ../metrics/B-CC.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['B-CC']["NNGen_data"] = float(os.popen(BC_evaluate_cmd).read().strip())
Rouge_evaluate_cmd = "python ../metrics/Rouge.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
rouge_str = os.popen(Rouge_evaluate_cmd).read().replace("'", "\"")
rouge_dict = json.loads(rouge_str)
results['Rouge-1']["NNGen_data"], results['Rouge-2']["NNGen_data"], results['Rouge-L']["NNGen_data"] = rouge_dict['ROUGE-1'], rouge_dict['ROUGE-2'], rouge_dict['ROUGE-L']
Meteor_evaluate_cmd = "python ../metrics/Meteor.py --ref_path {} --gen_path {}".format(ref_path, gen_path)
results['Meteor']["NNGen_data"] = float(os.popen(Meteor_evaluate_cmd).read().strip())
results

           B-Moses B-Norm  B-CC Rouge-1 Rouge-2 Rouge-L Meteor
NNGen_data   15.08  21.60 15.48   24.57   14.51   24.29  24.35